services:
  - type: web
    name: puzzle-gra-app
    env: node
    plan: starter
    buildCommand: |
      npm ci
      npm run setup-production
      npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:/opt/render/project/data/production.sqlite
      - key: SHOPIFY_API_KEY
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SHOPIFY_APP_URL
        value: https://puzzle-gra-app.onrender.com
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
    disk:
      name: puzzle-gra-data
      mountPath: /opt/render/project/data
      sizeGB: 1