# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "94e4636976915219baf9e1fb1ae77fc8"
name = "Puzzle Gra"
handle = "puzzle-gra"
application_url = "https://poland-stamp-foot-colored.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_customers"


[auth]
redirect_urls = ["https://poland-stamp-foot-colored.trycloudflare.com/auth/callback", "https://poland-stamp-foot-colored.trycloudflare.com/auth/shopify/callback", "https://poland-stamp-foot-colored.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
